version: '3.5'
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
  api:
    build: ./api
    command: ["./wait-for-it.sh", "db:5432;", "-t", "3", "--", "./app"]
    ports:
      - "3011:3011"
    env_file:
      - api.env
    depends_on:
      - db
    links:
      - db
  www:
    build: 
      context: ./www
      args:
        REACT_APP_NODE_ENV: 'production'
        REACT_APP_API_URL: 'http://localhost:3011'
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - "3000:80"
    env_file:
      - www.env
    depends_on:
      - api
    links:
      - api
